ERROR http-bio-8080-exec-2 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-10 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-10 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-10 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-10 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-1 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-1 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-8 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-10 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR Druid-ConnectionPool-Create-119918838 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode -1, state 08
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=172.21.14.118)(port=3306)(type=master) : Operation timed out
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:123)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect to address=(host=172.21.14.118)(port=3306)(type=master) : Operation timed out
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:706)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
Caused by: java.net.ConnectException: Operation timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:350)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	... 5 more
ERROR http-bio-8080-exec-8 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-9 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR Druid-ConnectionPool-Create-1970607394 com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://172.21.14.118:3306/taotao, errorCode 1049, state 42000
java.sql.SQLSyntaxErrorException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.Driver.connect(Driver.java:110)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1995)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Unknown database 'taotao'
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
	at org.mariadb.jdbc.Driver.connect(Driver.java:105)
	... 3 more
ERROR http-bio-8080-exec-8 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-8 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-8 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-8 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
ERROR http-bio-8080-exec-10 com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
